/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export enum PetByTypePetType {
    Cat = "Cat",
    Dog = "Dog",
}

export class PetByType extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "hunts" })
    hunts?: boolean;

    @SpeakeasyMetadata()
    @Expose({ name: "pet_type" })
    petType: PetByTypePetType;
}
